#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2010-2011 TUBITAK/UEKAE
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Please read the COPYING file.
#

import os,commands

from buildfarm.config import configuration as conf
from buildfarm import utils

CONF_FILE = "/etc/buildfarm/buildfarm.conf"

def check_config():
    try:
        print "Name: %s" % conf.name
        print "Release: %s" % conf.release
        print "Target architecture: %s" % conf.architecture
        print "Sub repository: %s" % conf.subrepository
        print "Repository directory: %s" % conf.repositorydir
    except KeyError:
        print "Please complete the missing fields in %s." % CONF_FILE
        return False
    else:
        print "Base configuration is OK."
        return True

def setup_repository():
    if conf.scm == "svn":
        remote_url = utils.get_remote_repository_url()
        local_url  = utils.get_local_repository_url()
        if os.system("svn info %s &> /dev/null" % local_url) > 0:
            os.chdir(local_url)
            print "%s will be checked out into %s" % (remote_url, local_url)
            os.system("svn checkout %s ." % remote_url)
        else:
            print "%s is checked out, skipping." % local_url

    # git deposundan dosya indirme özelliği sadece github altında denenmiştir.
    if conf.scm == "git":
        for branch in ["devel", "stable"]:
            utils.put_git_branch(branch) 
            remote_url = utils.get_remote_repository_url()
            local_url  = utils.get_local_repository_url()
            local_git  = utils.get_local_git_repository_url()
            if os.path.isdir("%s/.git" % local_git):
                print "%s/.git already exists." % local_git
            else:
                oldwd = os.getcwd()
                if os.path.isdir(local_git): os.system("rm -Rf %s" % local_git)
                os.chdir(os.path.dirname(local_git))
                print "%s will be checked out into %s" % (remote_url, local_git)
                os.system("git clone %s -b %s %s" % (remote_url, branch.replace("devel", "master"), local_git))
                os.system("rm -Rf %s/*" % local_url)
                os.chdir(local_git)
                os.system("cp -Rfp ./* %s" % local_url)
                os.system("rm -Rf %s/.git" % local_url)
                os.chdir(oldwd)
                   
if __name__ == "__main__":
    if check_config():
        utils.create_directories()
        setup_repository()
