#!/usr/bin/python
# -*- coding: utf-8 -*-

# Finds out possible leaks from buildfarm queues

import os
import sys
import pisi

from buildfarm.config import configuration as conf
from buildfarm import utils

if __name__ == "__main__":

    source_repo = utils.get_local_repository_url()
    binary_dir = utils.get_compiled_packages_directory()

    missing_pkgs = set()

    #pspec_list = os.popen("find %s -name 'pspec.xml'" % source_repo).read().strip().split("\n")
    pspec_list = utils.get_local_repo_pspecs()

    for pkg in pspec_list:
        try:
            spec = pisi.specfile.SpecFile(pkg)
        except Exception, e:
            sys.stderr.write("%s\n" % e)
        else:
            if conf.architecture in spec.source.excludeArch:
                continue

            ver = spec.history[0].version
            release = spec.history[0].release

            for subpkg in spec.packages:
                expected_file = pisi.util.package_filename(subpkg.name, ver, release)
                if os.path.exists(os.path.join(binary_dir, expected_file)):
                    break
            else:
                missing_pkgs.add(pkg)

    print "\n".join(sorted(list(missing_pkgs)))
